### ISSUE TITLE
Installation, version control

### ISSUE THREAD

**Issue by bitwombat** [nickjj/ansible-user#1]
Hi Nick,

ansible-galaxy has --roles-path so that I can put your cool roles right in my project's roles/ dir.

Better, a ./requirements.yml with:

````
---
- name: ansible-user
  src: https://github.com/nickjj/ansible-user
````

Then ansible-galaxy install -r requirements.yml

With ./ansible.cfg having:
````
[defaults]
roles_path = roles.galaxy:roles
````

Works a treat!

Would this be a useful edit to README.md and PR?

Cheers,
Greg (gbellinoz)

**Comment by nickjj** [comment]
Hi Greg,

That's a standard Ansible feature. I'm not sure if it belongs in this role's docs specifically.

You could also set the src as `nickjj.user` to grab it directly from the Galaxy instead of GitHub.
