### ISSUE TITLE
User once added to sudoers does not get removed

### ISSUE THREAD

**Issue by riteshpuj2013** [nickjj/ansible-user#3]
Hi,

Your ansible role fails in a particular scenario and fails to maintain state on the target server as per the value of "user_enable_passwordless_sudo".

Steps:
1. Set "user_enable_passwordless_sudo" to True and execute ansible script on target server.
2. Set "user_enable_passwordless_sudo" to False and execute ansible script on target server.
3. Observe that user is not removed from sudoers file on target server.

I have made change and tested on my local.
Would you accept PR for this issue?

--
Best Regards,
Ritesh

**Comment by nickjj** [comment]
Hi,

Thanks for the report. That sounds like a good PR. I'd merge it.

**Comment by riteshpuj2013** [comment]
Hi,

Thanks for quick response. Here you go: https://github.com/nickjj/ansible-user/pull/4

Let me know if you have any comments.
